#!/usr/bin/env python
import sys

input_file = sys.argv[1]
input_encoding = sys.argv[2]
output_file = sys.argv[3]
output_encoding = sys.argv[4]

f = open(input_file, 'r')
input_string = f.read().decode(input_encoding)
f.close()

output_string = ''
for i in input_string:
    output_string += chr(ord(i) + 1)

o = open(output_file, 'w')
o.write(output_string.encode(output_encoding))
o.close()
