#!/usr/bin/env python
import sys

# drop every 2nd characters
f = open('text-drop-each-2nd-character.txt', 'r')
sys.stdout.write(f.read()[::2])
f.close()

# reverse
f = open('reverse-me.fdp', 'r')
o = open('reversed.pdf', 'w')
o.write(f.read()[::-1])
f.close()
o.close()
